#!/bin/bash

# Setup script for SlurmManager iOS app Xcode project
# This script helps create a proper Xcode project with existing Swift files

echo "🚀 SlurmManager iOS App - Xcode Project Setup"
echo "=============================================="

# Check if we're in the right directory
if [ ! -d "SlurmManager" ]; then
    echo "❌ Error: Please run this script from the ios-app directory"
    echo "   Current directory: $(pwd)"
    echo "   Expected: ios-app directory containing SlurmManager folder"
    exit 1
fi

# Check if Xcode is installed
if ! command -v xcodebuild &> /dev/null; then
    echo "❌ Error: Xcode is not installed"
    echo "   Please install Xcode from the Mac App Store"
    exit 1
fi

echo "✅ Found SlurmManager directory"
echo ""

# Remove the placeholder project file
if [ -f "SlurmManager/SlurmManager.xcodeproj/project.pbxproj" ]; then
    echo "🗑  Removing placeholder project file..."
    rm -rf SlurmManager/SlurmManager.xcodeproj
fi

echo "📱 Creating Xcode project..."
echo ""
echo "Please follow these steps in Xcode:"
echo ""
echo "1️⃣  CREATING THE PROJECT:"
echo "   • Open Xcode"
echo "   • Click 'Create New Project' (or File → New → Project)"
echo "   • Choose: iOS → App"
echo "   • Click 'Next'"
echo ""
echo "2️⃣  PROJECT CONFIGURATION:"
echo "   • Product Name: SlurmManager"
echo "   • Team: Select your Apple ID"
echo "   • Organization Identifier: com.yourname (or your company)"
echo "   • Bundle Identifier: (will auto-fill)"
echo "   • Interface: SwiftUI"
echo "   • Language: Swift"
echo "   • Use Core Data: ❌ Unchecked"
echo "   • Include Tests: ✅ Checked"
echo "   • Click 'Next'"
echo ""
echo "3️⃣  SAVE LOCATION:"
echo "   ⚠️  IMPORTANT: Save in THIS directory:"
echo "   📁 $(pwd)"
echo "   • The project name should be 'SlurmManager'"
echo "   • This will create SlurmManager.xcodeproj here"
echo ""
echo "4️⃣  AFTER PROJECT CREATES:"
echo "   a) Delete these default files (right-click → Delete → Move to Trash):"
echo "      • ContentView.swift"
echo "      • Assets.xcassets (optional, keep if you want)"
echo ""
echo "   b) Add our Swift files:"
echo "      • Right-click on the SlurmManager folder in Xcode"
echo "      • Choose 'Add Files to \"SlurmManager\"...'"
echo "      • Navigate to: $(pwd)/SlurmManager"
echo "      • Select ALL folders (Models, Services, Views, etc.)"
echo "      • ✅ Copy items if needed: UNCHECKED"
echo "      • ✅ Create groups: CHECKED"
echo "      • ✅ Add to targets: SlurmManager CHECKED"
echo "      • Click 'Add'"
echo ""
echo "5️⃣  ADD PACKAGE DEPENDENCIES:"
echo "   • File → Add Package Dependencies..."
echo "   • Add these packages (one at a time):"
echo ""
echo "   📦 Alamofire (Networking):"
echo "      URL: https://github.com/Alamofire/Alamofire"
echo "      Version: Up to Next Major Version 5.8.0"
echo ""
echo "   📦 Starscream (WebSocket):"
echo "      URL: https://github.com/daltoniam/Starscream"
echo "      Version: Up to Next Major Version 4.0.0"
echo ""
echo "   📦 KeychainAccess (Secure Storage):"
echo "      URL: https://github.com/kishikawakatsumi/KeychainAccess"
echo "      Version: Up to Next Major Version 4.2.0"
echo ""
echo "6️⃣  CONFIGURE INFO.PLIST:"
echo "   • Select project → SlurmManager target → Info tab"
echo "   • Add these keys:"
echo "     - App Transport Security Settings"
echo "       → Exception Domains"
echo "         → localhost"
echo "           • NSExceptionAllowsInsecureHTTPLoads: YES"
echo "           • NSIncludesSubdomains: YES"
echo "     - Privacy - Face ID Usage Description:"
echo "       \"Authenticate to access your SLURM jobs securely\""
echo ""
echo "7️⃣  RUN THE APP:"
echo "   • Select target device (iPhone 15 Pro simulator recommended)"
echo "   • Press Cmd+R or click ▶️ Play button"
echo ""
echo "📝 Files to add from SlurmManager folder:"
ls -la SlurmManager/ | grep -E "swift$|/$" | grep -v "^\."
echo ""
echo "🎯 Quick command to open Xcode:"
echo "   open -a Xcode"
echo ""
echo "📚 Need help? Check the README:"
echo "   cat $(pwd)/../README.md"
echo ""
echo "✨ Once setup is complete, your app will:"
echo "   • Connect to your SLURM Manager API"
echo "   • Show real-time job updates"
echo "   • Support Face ID/Touch ID"
echo "   • Provide haptic feedback"
echo "   • Beautiful animations throughout"