# Test configuration with path restrictions enabled
hosts:
  - hostname: localhost
    work_dir: /tmp/test_work
    scratch_dir: /tmp/test_scratch

# Path restrictions for testing
path_restrictions:
  enabled: true
  max_size_gb: 1.0  # 1 GB limit
  allow_home: true
  allow_tmp: true
  allow_absolute: false

  # Only allow specific directories
  allowed_paths:
    - "/home/*/slurm-manager/*"
    - "/tmp/*"

  forbidden_paths:
    - "/etc"
    - "/sys"
    - "/proc"
    - "/.ssh"