<script lang="ts">
  import Icon from './Icon.svelte';
  import Status from './Status.svelte';
  import JobInspector from './JobInspector.svelte';
  import {hosts,keyFor,needsAttention,type Job,type JobTab,type Watcher} from '../data';
  let {jobs,watchers,search=$bindable(''),filter=$bindable('All jobs'),host=$bindable('All hosts'),selected=$bindable('atlas:48216'),full=$bindable(false),onrelaunch,onwatcher,onnotice}:{jobs:Job[];watchers:Watcher[];search?:string;filter?:string;host?:string;selected?:string;full?:boolean;onrelaunch:(job:Job)=>void;onwatcher:()=>void;onnotice:(m:string)=>void}=$props();
  let tab=$state<JobTab>('Overview');
  let descending=$state(true);
  const visible=$derived(jobs.filter(job=>(host==='All hosts'||job.host===host)&&(!search||`${job.name} ${job.id} ${job.project}`.toLowerCase().includes(search.toLowerCase()))&&(filter==='All jobs'||(filter==='Needs attention'?needsAttention(job):filter==='Historical'?!['Running','Pending'].includes(job.state):job.state===filter))).sort((a,b)=>descending?Number(b.id)-Number(a.id):Number(a.id)-Number(b.id)));
  const selectedJob=$derived(jobs.find(j=>keyFor(j)===selected));
  const tabs=$derived([{name:'All jobs',count:jobs.length},{name:'Running',count:jobs.filter(j=>j.state==='Running').length},{name:'Pending',count:jobs.filter(j=>j.state==='Pending').length},{name:'Needs attention',count:jobs.filter(needsAttention).length},{name:'Historical',count:jobs.filter(j=>!['Running','Pending'].includes(j.state)).length}]);
  function open(job:Job){selected=keyFor(job);tab=needsAttention(job)?'Output':'Overview';}
  function close(){selected='';full=false;history.replaceState({},'',`${location.pathname}#/jobs`);}
</script>

<div class="jobs-workspace" class:with-inspector={selectedJob&&!full} class:expanded-detail={full}>
  {#if !full}<section class="jobs-main" aria-label="Jobs list">
    <div class="view-tabs">{#each tabs as t}<button class:active={filter===t.name} onclick={()=>filter=t.name}>{t.name}<span class:attention-count={t.name==='Needs attention'&&t.count>0}>{t.count}</span></button>{/each}</div>
    <div class="filter-toolbar"><label class="search-field"><Icon name="Search" size={16}/><input placeholder="Search jobs…" aria-label="Search jobs" bind:value={search}/>{#if search}<button class="icon-button" aria-label="Clear search" onclick={()=>search=''}><Icon name="X" size={14}/></button>{/if}</label><label class="select-field"><Icon name="Server" size={15}/><select aria-label="Filter by host" bind:value={host}><option>All hosts</option>{#each hosts as h}<option>{h.name}</option>{/each}</select></label><button class="icon-button bordered" aria-label={descending?'Sort oldest first':'Sort newest first'} title={descending?'Newest first':'Oldest first'} onclick={()=>descending=!descending}><Icon name="ListFilter" size={17}/></button></div>
    {#if search||host!=='All hosts'}<div class="active-filters"><span>{visible.length} matching jobs</span><button class="text-button" onclick={()=>{search='';host='All hosts';}}>Clear filters <Icon name="X" size={13}/></button></div>{/if}
    <div class="job-groups">{#each hosts.filter(h=>visible.some(j=>j.host===h.name)) as h}<div class="host-group"><div class="host-group-heading"><div><Icon name="Server" size={15}/><strong>{h.name}</strong><span class="subtle small">{visible.filter(j=>j.host===h.name).length} jobs</span></div><span class="host-sync"><span class="connection-dot"></span>Up to date</span></div><div class="job-table" role="table" aria-label={`${h.name} jobs`}><div class="job-table-head" role="row"><span role="columnheader">Job</span><span role="columnheader">State</span><span role="columnheader">Resources</span><span role="columnheader">Runtime</span><span></span></div>{#each visible.filter(j=>j.host===h.name) as job}<button class="job-row" class:selected={selected===keyFor(job)} onclick={()=>open(job)} aria-label={`Inspect ${job.name}, ${job.state}, job ${job.id}`}><div class="job-name-cell"><div class="job-name-line"><span title={job.name}>{job.name}</span>{#if job.array}<span class="array-tag" title={`${job.array} array tasks`}><Icon name="Layers" size={12}/>{job.array}</span>{/if}</div><div class="job-secondary"><span class="mono">#{job.id}</span><span class="job-project">{job.project}</span></div></div><Status state={job.state}/><span class="resource-cell">{job.gpu?`${job.gpu} GPU`:`${job.cpus} CPU`}<small>{job.memory} GB</small></span><span class="runtime-cell">{job.runtime}{#if job.rank}<small>#{job.rank} in queue</small>{:else}<small>{job.submitted}</small>{/if}</span><Icon name="ChevronRight" size={15}/></button>{/each}</div></div>{/each}
    {#if !visible.length}<div class="empty-state"><span class="large-icon"><Icon name="Search" size={24}/></span><h3>No matching jobs</h3><p>Try a different search or clear your filters.</p><button class="button" onclick={()=>{search='';host='All hosts';filter='All jobs';}}>Clear all filters</button></div>{/if}</div>
    <div class="list-footer"><span>{visible.length} of {jobs.length} jobs</span><span>Historical window: last 14 days</span></div>
  </section>{/if}
  {#if selectedJob}<JobInspector job={selectedJob} watchers={watchers.filter(w=>w.host===selectedJob.host&&w.jobId===selectedJob.id)} bind:tab {full} onrestore={()=>{full=false;history.replaceState({},'',`${location.pathname}#/jobs`);}} onclose={close} onexpand={()=>{full=true;history.replaceState({},'',`${location.pathname}#/jobs/${selectedJob.host}/${selectedJob.id}`);}} {onrelaunch} {onwatcher} {onnotice}/>{/if}
</div>
