<script lang="ts">
  import { onDestroy } from 'svelte';
  import Icon from './Icon.svelte';
  import Modal from './Modal.svelte';
  import {hosts,scriptFromDraft,savePreference,type LaunchDraft} from '../data';
  let {draft=$bindable(),onlaunch,onnotice}:{draft:LaunchDraft;onlaunch:(draft:LaunchDraft)=>void;onnotice:(message:string)=>void}=$props();
  let review=$state(false);let launching=$state(false);let stage=$state(0);let tab=$state('Script');const selectedRecipe=$derived(draft.recipe);
  let launchTimer:ReturnType<typeof setTimeout>;
  const recipes=[{name:'Train potential',icon:'Zap',file:'train-potential.yaml',detail:'2 GPUs · 16 CPUs · 64 GB'},{name:'Structure search',icon:'Layers',file:'structure-search.yaml',detail:'64 CPUs · 128 GB'},{name:'Blank script',icon:'FileCode2',file:'Start from scratch',detail:'Your own SBATCH script'}];
  $effect(()=>savePreference('draft',draft));
  onDestroy(()=>clearTimeout(launchTimer));
  function useRecipe(name:string){draft.originalId=undefined;draft.recipe=name;if(name==='Structure search'){draft.name='structure-search';draft.host='borealis';draft.partition='compute';draft.gpu=0;draft.cpus=64;draft.memory=128;draft.hours=24;}else if(name==='Train potential'){draft.name='equivariant-potential-v4';draft.host='atlas';draft.partition='gpu-a100';draft.gpu=2;draft.cpus=16;draft.memory=64;draft.hours=12;}else{draft.name='my-job';draft.gpu=0;draft.cpus=1;draft.memory=4;draft.hours=1;}draft.script=name==='Blank script'?'#!/bin/bash\n\necho "Hello from ssync"':name==='Structure search'?'#!/bin/bash\n\npython search.py --config configs/structure-search.yaml':'#!/bin/bash\n\nmodule load cuda/12.4\nsource .venv/bin/activate\npython train.py --config configs/potential-v4.yaml';draft.script=scriptFromDraft(draft);}
  function submit(){launching=true;stage=0;const advance=()=>{stage++;if(stage<3)launchTimer=setTimeout(advance,650);else{review=false;launching=false;onlaunch(structuredClone($state.snapshot(draft)));}};launchTimer=setTimeout(advance,650);}
</script>
<div class="launch-sources"><div class="section-label">Start with a recipe <span class="subtle small">Potential v4 / .ssync</span></div><div class="recipe-grid">{#each recipes as recipe}<button class="recipe-card" class:active={selectedRecipe===recipe.name&&!draft.originalId} onclick={()=>useRecipe(recipe.name)}><span class="recipe-icon"><Icon name={recipe.icon} size={19}/></span><span><strong>{recipe.name}</strong><small>{recipe.file}</small><span class="recipe-detail">{recipe.detail}</span></span>{#if selectedRecipe===recipe.name&&!draft.originalId}<Icon name="Check" size={15}/>{/if}</button>{/each}</div></div>
{#if draft.originalId}<div class="notice"><Icon name="RefreshCw"/><div><strong>Manual relaunch of #{draft.originalId}</strong></div></div>{/if}
<form class="launch-form" onsubmit={(e)=>{e.preventDefault();review=true;}} onchange={(e)=>{if((e.target as HTMLElement).tagName!=='TEXTAREA')draft.script=scriptFromDraft(draft);}}>
  <div class="launch-grid"><section class="editor-panel"><div class="panel-header"><div class="editor-tabs"><button type="button" class:active={tab==='Script'} onclick={()=>tab='Script'}><Icon name="FileCode2" size={16}/>Job script</button><button type="button" class:active={tab==='Files'} onclick={()=>tab='Files'}><Icon name="Folder" size={16}/>Files & sync</button></div><span class="save-indicator"><Icon name="Check" size={13}/>Draft saved locally</span></div>
    {#if tab==='Script'}<div class="code-filebar"><span class="mono">{draft.name||'untitled'}.sh</span><span>Bash</span></div><div class="code-editor"><div class="editor-lines" aria-hidden="true">{#each draft.script.split('\n') as _,i}<span>{i+1}</span>{/each}</div><textarea aria-label="Job script" spellcheck="false" bind:value={draft.script}></textarea></div><div class="editor-status"><span><Icon name="Check" size={13}/>Editable script</span><span>UTF-8 <span>·</span> Bash</span></div>
    {:else}<div class="sync-panel"><h3>Source & destination</h3><label class="form-field">Local source directory<input required bind:value={draft.source} placeholder="/path/to/project"/></label><div class="sync-destination"><Icon name="ArrowRight"/><div><span class="small subtle">Remote destination</span><code>{draft.host}:/scratch/research/{draft.name}</code></div></div><div class="form-divider"></div><h3>Synchronization</h3><label class="checkbox-row"><input type="checkbox" bind:checked={draft.respectIgnore}/>Respect .gitignore</label><label class="checkbox-row"><input type="checkbox" bind:checked={draft.onlyChanged}/>Skip unchanged files</label><div class="file-preview"><div><Icon name="Folder" size={16}/>configs/<span>4 files</span></div><div><Icon name="Folder" size={16}/>src/<span>18 files</span></div><div><Icon name="FileCode2" size={16}/>train.py<span>12 KB</span></div><div class="subtle"><Icon name={draft.respectIgnore?'X':'Folder'} size={16}/>.venv/<span>{draft.respectIgnore?'Excluded':'Included'}</span></div><div class="subtle"><Icon name={draft.respectIgnore?'X':'Folder'} size={16}/>checkpoints/<span>{draft.respectIgnore?'Excluded':'Included'}</span></div></div><p class="small subtle">Sample sync · {draft.onlyChanged?'Changed files':'All files'} · {draft.respectIgnore?'.gitignore applied':'Including ignored files'}</p></div>{/if}
  </section>
  <aside class="configuration-panel"><div class="panel-header"><h3>Configuration</h3><Icon name="SlidersHorizontal" size={17}/></div><div class="configuration-body"><label class="form-field">Job name<input required bind:value={draft.name}/></label><div class="form-row"><label class="form-field">Host<select bind:value={draft.host}>{#each hosts as h}<option>{h.name}</option>{/each}</select></label><label class="form-field">Partition<select bind:value={draft.partition}><option>gpu-a100</option><option>gpu</option><option>compute</option></select></label></div><div class="form-divider"></div><div class="section-label">Resources<span class="small subtle">Per job</span></div><div class="form-row"><label class="form-field">GPUs<input type="number" min="0" max="8" required bind:value={draft.gpu}/></label><label class="form-field">CPUs<input type="number" min="1" max="256" required bind:value={draft.cpus}/></label></div><div class="form-row"><label class="form-field">Memory <span class="field-unit">GB</span><input type="number" min="1" max="2048" required bind:value={draft.memory}/></label><label class="form-field">Time limit <span class="field-unit">hours</span><input type="number" min="1" max="168" required bind:value={draft.hours}/></label></div><div class="resource-note"><Icon name="Server" size={15}/><span>{draft.host==='atlas'?'NVIDIA A100 · 80 GB per GPU':'General compute · CPU & GPU'}</span></div><div class="form-divider"></div><label class="form-field">Source directory<input required bind:value={draft.source}/></label><button class="text-button" type="button" onclick={()=>tab='Files'}>Review files & sync <Icon name="ArrowRight" size={14}/></button><div class="form-divider"></div><details class="advanced-fields"><summary>Advanced options</summary><label class="form-field">Account<input bind:value={draft.account} placeholder="Optional"/></label><label class="form-field">Exclude nodes<input bind:value={draft.exclude} placeholder="e.g. gpu-node-03"/></label><label class="form-field">Dependency<input bind:value={draft.dependency} placeholder="afterok:48216"/></label></details></div></aside></div>
  <div class="launch-bottom"><div><span class="icon-tile"><Icon name="Rocket" size={19}/></span><span><strong>{draft.name||'Untitled job'}</strong><small>{draft.host} · {draft.gpu?`${draft.gpu} GPU · `:''}{draft.cpus} CPU · {draft.memory} GB · {draft.hours}h</small></span></div><button class="button primary" type="submit">Review job <Icon name="ArrowRight" size={16}/></button></div>
</form>
{#if review}<Modal title={launching?'Launching sample job':'Review your job'} onclose={()=>review=false} busy={launching} wide><div class="review-content">{#if launching}<div class="launch-progress"><span class="large-icon"><Icon name="Rocket" size={26}/></span><h2>{['Preparing files','Synchronizing source','Submitting job'][stage]}</h2><p class="subtle">Simulating the launch workflow</p><div class="launch-stages">{#each ['Prepare','Synchronize','Submit'] as name,i}<span class:finished={stage>i} class:current={stage===i}><Icon name={stage>i?'Check':'Circle'} size={15}/>{name}</span>{/each}</div></div>{:else}<div class="review-title"><span class="icon-tile"><Icon name="FileCode2"/></span><div><h3>{draft.name}</h3><p class="small subtle">{draft.recipe||'Custom script'} · {draft.host}</p></div></div><div class="review-resources"><div><span>Host</span><strong>{draft.host}</strong></div><div><span>GPUs / CPUs</span><strong>{draft.gpu} / {draft.cpus}</strong></div><div><span>Memory</span><strong>{draft.memory} GB</strong></div><div><span>Time limit</span><strong>{draft.hours} hours</strong></div></div><div class="review-source"><span class="subtle small">Source directory</span><code>{draft.source}</code></div><details><summary>View final batch script</summary><pre class="script-preview">{draft.script}</pre></details><div class="notice"><Icon name="Eye" size={18}/><div><p>Adds a sample job. No files are transferred.</p></div></div><div class="modal-actions"><button class="button" onclick={()=>review=false}>Back to editing</button><button class="button primary" onclick={submit}><Icon name="Rocket" size={16}/>Simulate launch</button></div>{/if}</div></Modal>{/if}
