<script lang="ts">
  import Icon from './Icon.svelte';
  import Status from './Status.svelte';
  import Modal from './Modal.svelte';
  import type { Watcher, Job } from '../data';
  let {jobs,watchers=$bindable(),onjob,onnotice}:{jobs:Job[];watchers:Watcher[];onjob:(host:string,id:string)=>void;onnotice:(message:string)=>void}=$props();
  let selected=$state(1);let search=$state('');let filter=$state('All watchers');let editing=$state<Watcher|null>(null);let testText=$state('[12:54:12] checkpoint saved: checkpoints/epoch_184.pt');let testResult=$state('');
  const current=$derived(watchers.find(w=>w.id===selected));
  const visible=$derived(watchers.filter(w=>(filter==='All watchers'||w.state===filter)&&`${w.name} ${w.jobName} ${w.host}`.toLowerCase().includes(search.toLowerCase())));
  function toggle(w:Watcher){w.state=w.state==='Active'?'Paused':'Active';onnotice(`${w.name} ${w.state.toLowerCase()}`);}
  function edit(w?:Watcher){editing=w?structuredClone($state.snapshot(w)):{id:0,name:'',jobId:jobs[0].id,host:jobs[0].host,jobName:jobs[0].name,state:'Active',source:'stdout',pattern:'loss=(?<loss>[0-9.]+)',action:'Record metric',lastEvent:'Waiting for first match',count:0};testResult='';testText=w?.id===1?'[12:54:12] checkpoint saved: checkpoints/epoch_184.pt':'epoch=184 loss=0.0248';}
  function save(){if(!editing)return;const item={...editing,id:editing.id||Math.max(...watchers.map(w=>w.id),0)+1};if(editing.id)watchers=watchers.map(w=>w.id===item.id?item:w);else watchers=[...watchers,item];selected=item.id;editing=null;onnotice('Watcher saved');}
  function test(){try{const match=new RegExp(editing?.pattern||'').exec(testText);testResult=match?`Match found\n${JSON.stringify(match.groups||{match:match[0]},null,2)}\n\nPlanned action: ${editing?.action}`:'No match. Try adjusting the pattern or example output.';}catch(e){testResult=`Pattern error: ${(e as Error).message}`;}}
</script>
<div class="watcher-workspace"><section class="watcher-main"><div class="view-tabs">{#each ['All watchers','Active','Paused'] as state}<button class:active={filter===state} onclick={()=>filter=state}>{state}<span>{state==='All watchers'?watchers.length:watchers.filter(w=>w.state===state).length}</span></button>{/each}</div><div class="filter-toolbar"><label class="search-field"><Icon name="Search" size={16}/><input aria-label="Search watchers" placeholder="Find a watcher or job…" bind:value={search}/></label><button class="button primary" onclick={()=>edit()}><Icon name="Plus" size={16}/>New watcher</button></div><div class="watcher-list">{#each visible as watcher}<article class="watcher-row" class:selected={watcher.id===selected}><button class="watcher-select" onclick={()=>selected=watcher.id}><div class="watcher-list-title"><span class="icon-tile"><Icon name={watcher.action==='Record metric'?'Activity':watcher.action==='Send notification'?'Bell':'Workflow'} size={19}/></span><div><h3>{watcher.name}</h3><p>#{watcher.jobId} · {watcher.host}</p></div><Status state={watcher.state}/></div><div class="rule-summary"><span>{watcher.source==='Job state'?'Job ends':'Output matches'}</span><Icon name="ArrowRight" size={14}/><strong>{watcher.action}</strong></div><div class="watcher-last"><span><Icon name="CheckCheck" size={14}/>{watcher.lastEvent}</span><span>{watcher.count} events</span></div></button><div class="watcher-row-actions"><button class="text-button" onclick={()=>onjob(watcher.host,watcher.jobId)}>Open job <Icon name="ArrowUpRight" size={13}/></button><button class="icon-button" aria-label={`${watcher.state==='Active'?'Pause':'Resume'} ${watcher.name}`} onclick={()=>toggle(watcher)}><Icon name={watcher.state==='Active'?'Pause':'Play'} size={15}/></button></div></article>{/each}{#if !visible.length}<div class="empty-state"><Icon name="Eye" size={24}/><h3>No matching watchers</h3><button class="button" onclick={()=>{search='';filter='All watchers';}}>Clear filters</button></div>{/if}</div><div class="list-footer"><span>{visible.length} watchers</span></div></section>
{#if current}<aside class="watcher-inspector"><div class="panel-header"><span class="section-label">Rule</span><button class="button small" onclick={()=>edit(current)}>Edit rule</button></div><div class="watcher-inspector-body"><div class="inline-meta"><Status state={current.state}/><span class="small subtle">Every 30 seconds</span></div><h2>{current.name}</h2><button class="text-button" onclick={()=>onjob(current.host,current.jobId)}>#{current.jobId} on {current.host}<Icon name="ArrowUpRight" size={13}/></button><div class="rule-flow"><div class="rule-step"><span class="step-number">1</span><div><span class="eyebrow">WHEN</span><h3>{current.source==='Job state'?'The job finishes':'A pattern appears in '+current.source}</h3><code>{current.pattern}</code></div></div><div class="rule-step"><span class="step-number">2</span><div><span class="eyebrow">THEN</span><h3>{current.action}</h3></div></div></div><div class="form-divider"></div>{#if current.id===1||current.id===2}<div class="section-label">Latest capture</div><div class="variable-item"><span class="mono">{current.id===1?'path':'loss'}</span><code>{current.id===1?'checkpoints/epoch_184.pt':'0.0248'}</code></div>{:else}<p class="small subtle">{current.lastEvent}</p>{/if}<div class="form-divider"></div><div class="section-label">Recent activity</div><div class="timeline"><div class="timeline-item"><span class="timeline-icon green"><Icon name="Check" size={13}/></span><div><strong>{current.lastEvent}</strong>{#if current.count>0}<time>{current.count} recorded events</time>{/if}</div></div></div></div><div class="inspector-footer"><button class="button" onclick={()=>toggle(current)}><Icon name={current.state==='Active'?'Pause':'Play'} size={15}/>{current.state==='Active'?'Pause watcher':'Resume watcher'}</button></div></aside>{/if}</div>
{#if editing}<Modal title={editing.id?'Edit watcher':'Create watcher'} onclose={()=>editing=null} wide><form class="watcher-edit-form" onsubmit={(e)=>{e.preventDefault();save();}}><label class="form-field">Watcher name<input required bind:value={editing.name} placeholder="e.g. Training metrics"/></label><label class="form-field">Attached job<select value={`${editing.host}:${editing.jobId}`} onchange={(e)=>{const job=jobs.find(j=>`${j.host}:${j.id}`===e.currentTarget.value);if(job&&editing){editing.host=job.host;editing.jobId=job.id;editing.jobName=job.name;}}}>{#each jobs as job}<option value={`${job.host}:${job.id}`}>{job.name} · #{job.id} · {job.host}</option>{/each}</select></label><div class="form-row"><label class="form-field">Watch<select bind:value={editing.source}><option>stdout</option><option>stderr</option><option>Job state</option></select></label><label class="form-field">Action<select bind:value={editing.action}><option>Record metric</option><option>Send notification</option><option>Resubmit from checkpoint</option></select></label></div><label class="form-field">{editing.source==='Job state'?'Job states':'Match pattern'}<input required class="mono" bind:value={editing.pattern}/></label><div class="rule-preview"><div class="split"><h3>Try the rule</h3><span class="tag">Preview only</span></div><label class="form-field">Example output<textarea rows="2" bind:value={testText}></textarea></label><button class="button" type="button" onclick={test}><Icon name="Play" size={14}/>Preview match & action</button>{#if testResult}<pre class="test-result" aria-live="polite">{testResult}</pre>{/if}<p class="small subtle">This preview uses JavaScript patterns. No action is executed.</p></div><div class="modal-actions"><button class="button" type="button" onclick={()=>editing=null}>Cancel</button><button class="button primary" type="submit"><Icon name="Check" size={15}/>Save watcher</button></div></form></Modal>{/if}
