"""Compatibility facade for web API schemas."""

from .schemas import (
    ArrayJobGroup,
    CompleteJobDataResponse,
    FileMetadata,
    HostInfoWeb,
    JobInfoWeb,
    JobOutputResponse,
    JobStateWeb,
    JobStatusResponse,
    LaunchEventWeb,
    LaunchJobRequest,
    LaunchJobResponse,
    LaunchStatusResponse,
    NotificationDeviceRegistration,
    NotificationPreferences,
    NotificationPreferencesPatch,
    NotificationTestRequest,
    PartitionGpuTypeWeb,
    PartitionResourcesWeb,
    PartitionStatusResponse,
    SlurmDefaultsWeb,
    StatusQueryParams,
    WebPushKeys,
    WebPushSubscriptionRegistration,
    WebPushUnsubscribeRequest,
)

__all__ = [
    "ArrayJobGroup",
    "CompleteJobDataResponse",
    "FileMetadata",
    "HostInfoWeb",
    "JobInfoWeb",
    "JobOutputResponse",
    "JobStateWeb",
    "JobStatusResponse",
    "LaunchEventWeb",
    "LaunchJobRequest",
    "LaunchJobResponse",
    "LaunchStatusResponse",
    "NotificationDeviceRegistration",
    "NotificationPreferences",
    "NotificationPreferencesPatch",
    "NotificationTestRequest",
    "PartitionGpuTypeWeb",
    "PartitionResourcesWeb",
    "PartitionStatusResponse",
    "SlurmDefaultsWeb",
    "StatusQueryParams",
    "WebPushKeys",
    "WebPushSubscriptionRegistration",
    "WebPushUnsubscribeRequest",
]
